<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>MovingSprite.Program</StartupObject>
    <UseAppHost>true</UseAppHost>
    <HotReloadEnabled>false</HotReloadEnabled>
    <EnableDefaultLaunchSettingsFile>true</EnableDefaultLaunchSettingsFile>
  </PropertyGroup>

</Project>
